site_name: Publishing mit MKDocs
plugins:
  - search
theme:
  name: material
  language: de
  palette:
    scheme: slate
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets # include Files
  - footnotes
  - def_list
  - abbr # Abbreviations
  - pymdownx.tasklist
  - pymdownx.tabbed # Tabbed pages
  - pymdownx.superfences # Tabbed pages
  - attr_list #für Images
  - pymdownx.magiclink
  - admonition
